Add validations
elyor-doniyorov/form-validation-js pull request #2
Opened 2022-07-13 07:52 UTC by elyor-doniyorov

**In this branch 👇** 

`add validations using JavaScript;`

2022-07-15 15:16 UTC, OneSkool commented on form.js
> +    alert("job title should be in letters");
Collect errors in a single array and then display error message

2022-07-18 10:13 UTC, elyor-doniyorov commented on form.js
> +  if(jobTitle === "") {
done

2022-07-19 00:57 UTC, schohan requested changes
Where are error messages displayed? I would like to see it running on your laptop in our next meeting but make the requested changes.
In addition to this, try loading Form fields with JSON data as it would come from a backend API. Use a simple javascript function for it:

 `function load() {
    return {
       title: "some title",
       description: "description info",
       ....
    }
}`

2022-07-19 00:57 UTC, schohan commented on form.html
> +      <label for="jobStatus">jobStatus</label>
Labels should be named for users. So 'jobStatus' should be 'Job Status'.

2022-07-19 05:26 UTC, elyor-doniyorov commented
> Where are error messages displayed? I would like to see it running on your laptop in our next meeting but make the requested changes. In addition to this, try loading Form fields with JSON data as it would come from a backend API. Use a simple javascript function for it:
> 
> `function load() { return { title: "some title", description: "description info", .... } }`

2022-07-19 05:26 UTC, closed without merging